version: '3.8'

services:
  zai2api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zai2api
    ports:
      - "3007:3007"
    restart: unless-stopped
    networks:
      - zai2api-network

networks:
  zai2api-network:
    driver: bridge
