services:
  zai2api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zai2api
    ports:
      - "${PORT}:${PORT}"
    environment:
      # 上游 API 配置
      - UPSTREAM_URL=${UPSTREAM_URL}
      - UPSTREAM_TOKEN=${UPSTREAM_TOKEN}
      
      # 认证配置
      - DEFAULT_KEY=${DEFAULT_KEY}
      - ANON_TOKEN_ENABLED=${ANON_TOKEN_ENABLED}
      
      # 模型配置
      - DEFAULT_MODEL_NAME=${DEFAULT_MODEL_NAME}
      - THINKING_MODEL_NAME=${THINKING_MODEL_NAME}
      - SEARCH_MODEL_NAME=${SEARCH_MODEL_NAME}
      
      # 服务配置
      - PORT=:${PORT}
      - DEBUG_MODE=${DEBUG_MODE}
      - THINK_TAGS_MODE=${THINK_TAGS_MODE}
    restart: unless-stopped
    networks:
      - zai2api-network

networks:
  zai2api-network:
    driver: bridge
